### ISSUE TITLE
Only effective in the source code view, not effective in the read view.

### ISSUE THREAD

**Issue by zhoulonghao520** [marcel-goldammer/obsidian-keyword-highlighter#1]
<img width="1488" alt="image" src="https://github.com/marcel-goldammer/obsidian-keyword-highlighter/assets/144794808/e82f5a49-46b9-4f19-8959-6e280e861eef">

<img width="1474" alt="image" src="https://github.com/marcel-goldammer/obsidian-keyword-highlighter/assets/144794808/f070c4db-9b12-4561-b405-c3b3246d5c45">

ObisidanV1.3.5

**Comment by marcel-goldammer** [comment]
Hi, the intention was to only use the highlighting in editor mode. But I try to implement this in reader mode aswell.

**Comment by marcel-goldammer** [comment]
I created a new release 1.1.0. Feel free to try this and provide feedback ;)
