### ISSUE TITLE
[feature-request] add keyword command

### ISSUE THREAD

**Issue by marcel-goldammer** [marcel-goldammer/obsidian-keyword-highlighter#11]
Create a command to easily add a new keyword. 

If text is already selected use this selection as keyword.

**Comment by fornewfork** [comment]
Could we consider the delete keyword command? In certain scenarios, we may highlight multiple keywords for temporary reading, but later we don't need these keywords. Therefore, the abilities to quickly add and remove highlighted keywords  will be helpful.
