### ISSUE TITLE
[feature-request] Allow Different Configurations for Various Files in Managing Keywords

### ISSUE THREAD

**Issue by nidongpinyinme** [marcel-goldammer/obsidian-keyword-highlighter#15]
### Description

I noticed that the plugin currently uses a configuration file to manage registered keywords. Is it possible to use different configurations for different files?
Thank you very much for your hard work.
 I used GPT for the translation, so please forgive any inaccuracies in the translation.

### Proposed Solution

use current config for global, and for each file need special control create a  local config for it.

**Comment by marcel-goldammer** [comment]
Handling different kinds of configuration withing different folders is too complicated. Sorry.
