### ISSUE TITLE
[bug] callout block icon disappear

### ISSUE THREAD

**Issue by HNO333333** [marcel-goldammer/obsidian-keyword-highlighter#16]
### Description

after enabling this plugin, the callout block will not show the icon!

### To Reproduce

1. create a new callout blcok
> [!note]
2. 
3. 
4. 
...

### Expected Behavior

common callout block

### Actual Behavior

callout block but no idon
![image](https://github.com/marcel-goldammer/obsidian-keyword-highlighter/assets/92591395/937e8c36-eafe-4de7-a1e8-fb28f0079323)

### Environment

- Obsidian Version: [e.g. 1.4.0]
- Plugin Version: [e.g. 1.0.0]
- Reader mode or Preview mode

**Comment by marcel-goldammer** [comment]
Thanks! I can reproduce this bug. I will take a close look at it

**Comment by marcel-goldammer** [comment]
I had to rewrite the highlighter feature for the reader mode. It seems like the replacement of innerHTML caused the problem. Please try out the new version and provide some feedback about performance aswell.

**Comment by HNO333333** [comment]
Thank you for your hard work! Problem solved!
