### ISSUE TITLE
[feature-request] add hot key to add selected word in text to key-words list

### ISSUE THREAD

**Issue by aikruger** [marcel-goldammer/obsidian-keyword-highlighter#17]
### Description

it would help enormously to be able to add a keyword to the list by highlighting a word in a note and then have a command that adds it to the key-word list 

### Proposed Solution

Add command functionality that can be trigger via hot key and/or button to a selected text or requests a word if none is selected. But this adds the word to a list, which itself might be in a folder in the vault.

**Comment by marcel-goldammer** [comment]
Hi, please have a look at #11 . That seems to match your requirements. I will create a new release soon.

**Comment by aikruger** [comment]
Could I add to this the possibility of adding synonyms to the keyword input box separated perhaps by a comma? So: alliances, alliance, ally, allies are all highlighted the same by putting in the same box

**Comment by marcel-goldammer** [comment]
Please open another feature request. 

In general I am thinking about a little restructure of that settings tab. I think about global and keyword specific settings. In the beginning a single configuration line per keyword was totally enough. But now the settings grow and I might need some multi line configuration.
