### ISSUE TITLE
[feature-request] Can we have an option to set no highlight so that you can just change text color?

### ISSUE THREAD

**Issue by hyperphysin** [marcel-goldammer/obsidian-keyword-highlighter#26]
### Description

an option to set no highlight

### Proposed Solution

maybe transparent highlight?

**Comment by marcel-goldammer** [comment]
The obsidian color picker does not support transparency. I want to keep the settings page quite simple, so I think I cannot support this either. A workaround could be to set the background color the same as your editors background color in obsidian.

Otherwise feel free to create a pull request for this feature!

**Comment by marcel-goldammer** [comment]
<img width="917" alt="grafik" src="https://github.com/marcel-goldammer/obsidian-keyword-highlighter/assets/15702400/ebea1608-df02-4b51-b841-e4c085b753f1">
<img width="1204" alt="grafik" src="https://github.com/marcel-goldammer/obsidian-keyword-highlighter/assets/15702400/ef03b912-f1b0-4e3d-aeb2-07ddd38aed02">

What do you think about this checkboxes? I do not know if this might be a little confusing...

**Comment by ferileho** [comment]
That's exactly what I meant with check boxes. I don't know if it will be confusing, but I think everyone can test what it does...

**Comment by marcel-goldammer** [comment]
I just released v1.3.2 that implements these new options.

**Comment by ferileho** [comment]
> I just released v1.3.2 that implements these new options.

Thank you
Now it works perfectly fine :)

**Comment by hyperphysin** [comment]
> I just released v1.3.2 that implements these new options.

Thank you! I works perfectly. 👍
